[svn] Improvements:     Simplified the configuration step for the parallel version. We don't require     anymore the mpi library name, just to --enable-mpi and pass the appropriate     mpicc or CFLAGS and LIBS.
    Updated the INSTALL instructions in the source.

    Updated the version number.

diff --git a/ocamlmpi/configure b/ocamlmpi/configure
--- a/ocamlmpi/configure
+++ b/ocamlmpi/configure
@@ -630,7 +630,6 @@ USEGRAPHICS
 USEINTERFACE
 USESHAREDHD
 USEPARALLEL
-MPILNAME
 OCAML
 OCAMLC
 OCAMLOPT
@@ -1221,9 +1220,9 @@ if test -n "$ac_init_help"; then
 Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
-  --enable-mpi=libname    Turns on parallel support using MPI, with the
-                          library name libname. When using MPI remember to set
-                          CC to mpicc.
+  --enable-mpi            Turns on parallel support using MPI. When using MPI
+                          remember to set CC to the appropriate mpicc
+                          compiler.
 
 Some influential environment variables:
   CC          C compiler command
@@ -2714,94 +2713,6 @@ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 
 
 
-
-# Check whether --enable-mpi was given.
-if test "${enable_mpi+set}" = set; then
-  enableval=$enable_mpi; USEPARALLEL=true; MPILNAME=$enableval
-else
-  USEPARALLEL=false
-fi
-
-
-
-
-if test $USEPARALLEL = "true"; then
-  as_ac_Lib=`echo "ac_cv_lib_$MPILNAME''_MPI_Init" | $as_tr_sh`
-{ echo "$as_me:$LINENO: checking for MPI_Init in -l$MPILNAME" >&5
-echo $ECHO_N "checking for MPI_Init in -l$MPILNAME... $ECHO_C" >&6; }
-if { as_var=$as_ac_Lib; eval "test \"\${$as_var+set}\" = set"; }; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-l$MPILNAME  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char MPI_Init ();
-int
-main ()
-{
-return MPI_Init ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  eval "$as_ac_Lib=yes"
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	eval "$as_ac_Lib=no"
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-ac_res=`eval echo '${'$as_ac_Lib'}'`
-	       { echo "$as_me:$LINENO: result: $ac_res" >&5
-echo "${ECHO_T}$ac_res" >&6; }
-if test `eval echo '${'$as_ac_Lib'}'` = yes; then
-  LIBS="-l$MPILNAME $LIBS"
-else
-  { { echo "$as_me:$LINENO: error: In order to compile the parallel version, an implemention of MPI is required. However, I failed while checking for $MPILNAME.
-See \`config.log' for more details." >&5
-echo "$as_me: error: In order to compile the parallel version, an implemention of MPI is required. However, I failed while checking for $MPILNAME.
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-fi
-
-
 for ac_prog in ocaml
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
@@ -3012,12 +2923,33 @@ fi
   test -n "$OCAMLTOP" && break
 done
 
+
 # Checks for libraries.
+
+# Check whether --enable-mpi was given.
+if test "${enable_mpi+set}" = set; then
+  enableval=$enable_mpi; USEPARALLEL=true
+else
+  USEPARALLEL=false
+fi
+
+
+#AC_MSG_CHECKING([Checking for MPI usability])
+#AC_LANG_CONFTEST([AC_LANG_PROGRAM([],[[MPI_Init()]])])
+#$CC -E -dD conftest.c -o -
+#AC_MSG_RESULT([The results of the test is $?])
+#if [ ! $? ]; then
+#    AC_MSG_FAILURE([I could not compile the MPI test program with your configuration.])
+#fi
+
+#AS_IF([test $USEPARALLEL = "true"], [AC_CHECK_LIB([$MPILNAME], [MPI_Init],
+#      [LIBS="-l$MPILNAME $LIBS"], [AC_MSG_FAILURE([In order to compile the parallel version, an implemention of MPI is required. However, I failed while checking for $MPILNAME.])])])
 # Checks for header files.
 
 # Checks for typedefs, structures, and compiler characteristics.
 
 # Checks for library functions.
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -4255,7 +4187,6 @@ USEGRAPHICS!$USEGRAPHICS$ac_delim
 USEINTERFACE!$USEINTERFACE$ac_delim
 USESHAREDHD!$USESHAREDHD$ac_delim
 USEPARALLEL!$USEPARALLEL$ac_delim
-MPILNAME!$MPILNAME$ac_delim
 OCAML!$OCAML$ac_delim
 OCAMLC!$OCAMLC$ac_delim
 OCAMLOPT!$OCAMLOPT$ac_delim
@@ -4268,7 +4199,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 62; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 61; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
